###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /app
        container_name: mysql
        volumes:
            - './app:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=petshop
            - MYSQL_USER=mmazoni
            - MYSQL_PASSWORD=password
        ports:
            - '31001:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - './app:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '31000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /app
        volumes:
            - './app:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
        environment:
          PHP_IDE_CONFIG: "serverName=Docker"
