name: Build PHPCodeSniffer

on: pull_request

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out repository
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      # - uses: shivammathur/setup-php@v2
      #   name: Setup PHP
      #   with:
      #     php-version: '7.3'
      #     tools: "phpcs, composer:v1"
      #   env:
      #     runner: self-hosted # This config is necessary to run act (Github Action Locally)
      # - name: Install PHP_CodeSniffer
      #   run: |
      #     curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
      #     php phpcs.phar --version
      - name: Run PHP_CodeSniffer
        uses: rtCamp/action-phpcs-code-review@v2
        env:
          GH_BOT_TOKEN: ${{ secrets.SNIFFER_PERSONAL_TOKEN }}
          SKIP_FOLDERS: "app/migrations"
          PHPCS_SNIFFS_EXCLUDE: ""
          PHPCS_FILE_PATH: phpcs.phar
          PHPCS_STANDARD_FILE_NAME: dev/ruleset.xml
        #with:
        #  files: "**.php"
        #  phpcs_path: php phpcs.phar
        #  standard: dev/ruleset.xml
